// src/app/view/CameraView.jsx
import React from 'react';
import BaseView from './BaseView';

class CameraView extends BaseView {

  /**
   * Use this lifeycle method to add event listeners
   */
  componentDidMount() {
    this.props.renderer.viewWillAppear();
  }

  componentWillUnmount() {
    this.props.renderer.viewWillDisappear();
  }

  render() {

    const domElement = this.props.renderer.render();

    return (
      <div
        id="camera-view"
        ref={(ref) => {
          if (ref) {
            domElement.className = 'three-canvas';
            ref.appendChild(domElement);
          }
        }}
      />
    );
  }

}

export default CameraView;

// src/app/vue/CameraView.vue
<template>
<div id="camera-view" v-canvas="renderer">
</div>
</template>

<script>
export default {

  props: ['renderer'],
  directives: {
    canvas: {
      bind: function(el, binding) {
        const renderer = binding.value;
        const domElement = renderer.dom;
        domElement.className = 'three-canvas';
        el.appendChild(domElement);
      }
    }
  },
  mounted: function() {
    this.renderer.viewWillAppear();
  },

  destroyed: function() {
    this.renderer.viewWillDisappear();
  }

}
</script>

<style scoped>
</style>
